// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedNt1MLV2v3LcNCRNVDVS2mgF3wIezgA',
    appId: '1:447213836415:android:767883d8433ac38959474a',
    messagingSenderId: '447213836415',
    projectId: 'arab-ween-app',
    databaseURL: 'https://arab-ween-app-default-rtdb.firebaseio.com',
    storageBucket: 'arab-ween-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmhpElFSNfZU8_VH13qovEz1gQ86nwfDQ',
    appId: '1:447213836415:ios:2118c41d443c65a859474a',
    messagingSenderId: '447213836415',
    projectId: 'arab-ween-app',
    databaseURL: 'https://arab-ween-app-default-rtdb.firebaseio.com',
    storageBucket: 'arab-ween-app.firebasestorage.app',
    androidClientId: '447213836415-jgobtfo3i95uvo1bv8e311vn2nrnt406.apps.googleusercontent.com',
    iosClientId: '447213836415-qbs6aophl5pvc68efriipdgqfigb5dk5.apps.googleusercontent.com',
    iosBundleId: 'com.arabween',
  );

}